apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: kube-kata
          image: nubificus/kata-vaccel-all-deploy:0.0.1
